COVID_DATA_URL: "https://data.covid19india.org/v4/min/data.min.json"
MONGO_DB_URL : "<insert your db endpoint here with access key>"
DATABASE : "<Database Name>"
COLLECTION : "<Collection Name>"
REDIS_URL : ""
USER_LOCATION_URL : "http://ip-api.com/json/"


# "http://api.ipstack.com/"